// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footers → Footer Items*
 */
export interface FootersDocumentDataFooterItemsItem {
  /**
   * Name field in *Footers → Footer Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footers.footer_items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Footers → Footer Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footers.footer_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footers documents
 */
interface FootersDocumentData {
  /**
   * Name field in *Footers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footers.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Footer Items field in *Footers*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footers.footer_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_items: prismic.GroupField<
    Simplify<FootersDocumentDataFooterItemsItem>
  >;
}

/**
 * Footers document from Prismic
 *
 * - **API ID**: `footers`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FootersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FootersDocumentData>,
    "footers",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | CaseStudiesSectionSlice
  | EventSectionSlice
  | NewMediaSectionSlice
  | VolunteerSectionSlice
  | ActiveSectionSlice
  | VisionFutureSectionSlice
  | IndustrySectionSlice
  | ServiceSectionSlice
  | SolutionsGloballySectionSlice
  | AboutUsSectionSlice
  | HeroSectionSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Navigation → Child Link*
 */
export interface NavigationDocumentDataChildLinkItem {
  /**
   * Link Name field in *Navigation → Child Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.child_link[].link_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_name: prismic.KeyTextField;

  /**
   * Link Href field in *Navigation → Child Link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.child_link[].link_href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_href: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Name field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Child Link field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.child_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  child_link: prismic.GroupField<Simplify<NavigationDocumentDataChildLinkItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | PreviousNewSlice
  | LatestNewsSlice
  | ExploreNewSlice
  | HeroSectionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Socicals*
 */
export interface SettingsDocumentDataSocicalsItem {
  /**
   * Social Icon field in *Settings → Socicals*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socicals[].social_icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  social_icon: prismic.SelectField<"facebook" | "instagram" | "x" | "youtube">;

  /**
   * Social Linnk field in *Settings → Socicals*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socicals[].social_linnk
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_linnk: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Settings → Navigations*
 */
export interface SettingsDocumentDataNavigationsItem {
  /**
   * Navigation Item field in *Settings → Navigations*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigations[].navigation_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_item: prismic.ContentRelationshipField;
}

/**
 * Item in *Settings → Footer Links*
 */
export interface SettingsDocumentDataFooterLinksItem {
  /**
   * Footer Links field in *Settings → Footer Links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_links[].footer_links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footer_links: prismic.ContentRelationshipField<"footers">;
}

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Light Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.light_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  light_logo: prismic.ImageField<never>;

  /**
   * Socicals field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socicals[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socicals: prismic.GroupField<Simplify<SettingsDocumentDataSocicalsItem>>;

  /**
   * Navigations field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigations: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationsItem>
  >;

  /**
   * Banner Title field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.banner_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  banner_title: prismic.RichTextField;

  /**
   * Banner Text Button field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.banner_text_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  banner_text_button: prismic.KeyTextField;

  /**
   * Title field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Copyright Text field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright_text: prismic.RichTextField;

  /**
   * Footer Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterLinksItem>
  >;

  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice> /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: settings.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FootersDocument
  | HomepageDocument
  | NavigationDocument
  | PageDocument
  | SettingsDocument;

/**
 * Item in *AboutUsSection → Default → Primary → Abouts*
 */
export interface AboutUsSectionSliceDefaultPrimaryAboutsItem {
  /**
   * Title field in *AboutUsSection → Default → Primary → Abouts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_section.default.primary.abouts[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *AboutUsSection → Default → Primary → Abouts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_section.default.primary.abouts[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AboutUsSection → Default → Primary*
 */
export interface AboutUsSectionSliceDefaultPrimary {
  /**
   * Name field in *AboutUsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *AboutUsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *AboutUsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Abouts field in *AboutUsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_section.default.primary.abouts[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  abouts: prismic.GroupField<
    Simplify<AboutUsSectionSliceDefaultPrimaryAboutsItem>
  >;

  /**
   * Button Text field in *AboutUsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_section.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for AboutUsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsSection*
 */
type AboutUsSectionSliceVariation = AboutUsSectionSliceDefault;

/**
 * AboutUsSection Shared Slice
 *
 * - **API ID**: `about_us_section`
 * - **Description**: AboutUsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSectionSlice = prismic.SharedSlice<
  "about_us_section",
  AboutUsSectionSliceVariation
>;

/**
 * Primary content in *ActiveSection → Default → Primary*
 */
export interface ActiveSectionSliceDefaultPrimary {
  /**
   * Name field in *ActiveSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: active_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *ActiveSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: active_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for ActiveSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActiveSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ActiveSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ActiveSection*
 */
type ActiveSectionSliceVariation = ActiveSectionSliceDefault;

/**
 * ActiveSection Shared Slice
 *
 * - **API ID**: `active_section`
 * - **Description**: ActiveSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActiveSectionSlice = prismic.SharedSlice<
  "active_section",
  ActiveSectionSliceVariation
>;

/**
 * Item in *CaseStudiesSection → Default → Primary → Casestudies*
 */
export interface CaseStudiesSectionSliceDefaultPrimaryCasestudiesItem {
  /**
   * Name field in *CaseStudiesSection → Default → Primary → Casestudies*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_section.default.primary.casestudies[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Description field in *CaseStudiesSection → Default → Primary → Casestudies*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_section.default.primary.casestudies[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *CaseStudiesSection → Default → Primary → Casestudies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_section.default.primary.casestudies[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *CaseStudiesSection → Default → Primary*
 */
export interface CaseStudiesSectionSliceDefaultPrimary {
  /**
   * Name field in *CaseStudiesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *CaseStudiesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Casestudies field in *CaseStudiesSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_section.default.primary.casestudies[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  casestudies: prismic.GroupField<
    Simplify<CaseStudiesSectionSliceDefaultPrimaryCasestudiesItem>
  >;

  /**
   * Background field in *CaseStudiesSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_section.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;
}

/**
 * Default variation for CaseStudiesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudiesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CaseStudiesSection*
 */
type CaseStudiesSectionSliceVariation = CaseStudiesSectionSliceDefault;

/**
 * CaseStudiesSection Shared Slice
 *
 * - **API ID**: `case_studies_section`
 * - **Description**: CaseStudiesSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSectionSlice = prismic.SharedSlice<
  "case_studies_section",
  CaseStudiesSectionSliceVariation
>;

/**
 * Primary content in *EventSection → Default → Primary*
 */
export interface EventSectionSliceDefaultPrimary {
  /**
   * Title field in *EventSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for EventSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventSection*
 */
type EventSectionSliceVariation = EventSectionSliceDefault;

/**
 * EventSection Shared Slice
 *
 * - **API ID**: `event_section`
 * - **Description**: EventSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventSectionSlice = prismic.SharedSlice<
  "event_section",
  EventSectionSliceVariation
>;

/**
 * Primary content in *ExploreNew → Default → Primary*
 */
export interface ExploreNewSliceDefaultPrimary {
  /**
   * Name field in *ExploreNew → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: explore_new.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *ExploreNew → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: explore_new.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Button Text field in *ExploreNew → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: explore_new.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for ExploreNew Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExploreNewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExploreNewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ExploreNew*
 */
type ExploreNewSliceVariation = ExploreNewSliceDefault;

/**
 * ExploreNew Shared Slice
 *
 * - **API ID**: `explore_new`
 * - **Description**: ExploreNew
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExploreNewSlice = prismic.SharedSlice<
  "explore_new",
  ExploreNewSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Background field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Primary Button Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * Secondary Button Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_text: prismic.KeyTextField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → HeroNews → Primary*
 */
export interface HeroSectionSliceHeroNewsPrimary {
  /**
   * Title field in *HeroSection → HeroNews → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.heroNews.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Background field in *HeroSection → HeroNews → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.heroNews.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Breadcrum Previous field in *HeroSection → HeroNews → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.heroNews.primary.breadcrum_previous
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  breadcrum_previous: prismic.KeyTextField;

  /**
   * Breadcrum Current field in *HeroSection → HeroNews → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.heroNews.primary.breadcrum_current
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  breadcrum_current: prismic.KeyTextField;
}

/**
 * HeroNews variation for HeroSection Slice
 *
 * - **API ID**: `heroNews`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceHeroNews = prismic.SharedSliceVariation<
  "heroNews",
  Simplify<HeroSectionSliceHeroNewsPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation =
  | HeroSectionSliceDefault
  | HeroSectionSliceHeroNews;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *IndustrySection → Default → Primary → Industrys*
 */
export interface IndustrySectionSliceDefaultPrimaryIndustrysItem {
  /**
   * Icon field in *IndustrySection → Default → Primary → Industrys*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: industry_section.default.primary.industrys[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    | "agriculture"
    | "banking_and_inance"
    | "construction_and_real_estate"
    | "e_commerce_and_retail"
    | "education_higher_research"
    | "healthcare_and_life_sciences"
    | "industrial_manufacturing"
    | "logistics_and_supply_chain"
    | "professional_services"
  >;

  /**
   * Name field in *IndustrySection → Default → Primary → Industrys*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industry_section.default.primary.industrys[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *IndustrySection → Default → Primary*
 */
export interface IndustrySectionSliceDefaultPrimary {
  /**
   * Name field in *IndustrySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industry_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *IndustrySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industry_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *IndustrySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industry_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *IndustrySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industry_section.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Industrys field in *IndustrySection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: industry_section.default.primary.industrys[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  industrys: prismic.GroupField<
    Simplify<IndustrySectionSliceDefaultPrimaryIndustrysItem>
  >;
}

/**
 * Default variation for IndustrySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndustrySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IndustrySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IndustrySection*
 */
type IndustrySectionSliceVariation = IndustrySectionSliceDefault;

/**
 * IndustrySection Shared Slice
 *
 * - **API ID**: `industry_section`
 * - **Description**: IndustrySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndustrySectionSlice = prismic.SharedSlice<
  "industry_section",
  IndustrySectionSliceVariation
>;

/**
 * Primary content in *LatestNews → Default → Primary*
 */
export interface LatestNewsSliceDefaultPrimary {
  /**
   * Name field in *LatestNews → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *LatestNews → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Button Text field in *LatestNews → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for LatestNews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestNewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LatestNewsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LatestNews*
 */
type LatestNewsSliceVariation = LatestNewsSliceDefault;

/**
 * LatestNews Shared Slice
 *
 * - **API ID**: `latest_news`
 * - **Description**: LatestNews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestNewsSlice = prismic.SharedSlice<
  "latest_news",
  LatestNewsSliceVariation
>;

/**
 * Primary content in *NewMediaSection → Default → Primary*
 */
export interface NewMediaSectionSliceDefaultPrimary {
  /**
   * Name field in *NewMediaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_media_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *NewMediaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_media_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *NewMediaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_media_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *NewMediaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_media_section.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for NewMediaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewMediaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewMediaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewMediaSection*
 */
type NewMediaSectionSliceVariation = NewMediaSectionSliceDefault;

/**
 * NewMediaSection Shared Slice
 *
 * - **API ID**: `new_media_section`
 * - **Description**: NewMediaSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewMediaSectionSlice = prismic.SharedSlice<
  "new_media_section",
  NewMediaSectionSliceVariation
>;

/**
 * Primary content in *PreviousNews → Default → Primary*
 */
export interface PreviousNewSliceDefaultPrimary {
  /**
   * Name field in *PreviousNews → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: previous_new.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *PreviousNews → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: previous_new.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for PreviousNews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreviousNewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PreviousNewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PreviousNews*
 */
type PreviousNewSliceVariation = PreviousNewSliceDefault;

/**
 * PreviousNews Shared Slice
 *
 * - **API ID**: `previous_new`
 * - **Description**: PreviousNew
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreviousNewSlice = prismic.SharedSlice<
  "previous_new",
  PreviousNewSliceVariation
>;

/**
 * Item in *ServiceSection → Default → Primary → Services*
 */
export interface ServiceSectionSliceDefaultPrimaryServicesItem {
  /**
   * Icon field in *ServiceSection → Default → Primary → Services*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"overview" | "fintech" | "solution">;

  /**
   * Title field in *ServiceSection → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ServiceSection → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ServiceSection → Default → Primary*
 */
export interface ServiceSectionSliceDefaultPrimary {
  /**
   * Background field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Name field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Services field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<
    Simplify<ServiceSectionSliceDefaultPrimaryServicesItem>
  >;

  /**
   * Image field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ServiceSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceSection*
 */
type ServiceSectionSliceVariation = ServiceSectionSliceDefault;

/**
 * ServiceSection Shared Slice
 *
 * - **API ID**: `service_section`
 * - **Description**: ServiceSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSectionSlice = prismic.SharedSlice<
  "service_section",
  ServiceSectionSliceVariation
>;

/**
 * Item in *SolutionsGloballySection → Default → Primary → Carousel*
 */
export interface SolutionsGloballySectionSliceDefaultPrimaryCarouselItem {
  /**
   * Media field in *SolutionsGloballySection → Default → Primary → Carousel*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_globally_section.default.primary.carousel[].media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *SolutionsGloballySection → Default → Primary*
 */
export interface SolutionsGloballySectionSliceDefaultPrimary {
  /**
   * Name field in *SolutionsGloballySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_globally_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *SolutionsGloballySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_globally_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *SolutionsGloballySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_globally_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Primary Button Text field in *SolutionsGloballySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_globally_section.default.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * Secondary Button Text field in *SolutionsGloballySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_globally_section.default.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * Background field in *SolutionsGloballySection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_globally_section.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Carousel field in *SolutionsGloballySection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_globally_section.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<SolutionsGloballySectionSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for SolutionsGloballySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SolutionsGloballySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SolutionsGloballySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SolutionsGloballySection*
 */
type SolutionsGloballySectionSliceVariation =
  SolutionsGloballySectionSliceDefault;

/**
 * SolutionsGloballySection Shared Slice
 *
 * - **API ID**: `solutions_globally_section`
 * - **Description**: SolutionsGloballySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SolutionsGloballySectionSlice = prismic.SharedSlice<
  "solutions_globally_section",
  SolutionsGloballySectionSliceVariation
>;

/**
 * Item in *VisionFutureSection → Default → Primary → Contents*
 */
export interface VisionFutureSectionSliceDefaultPrimaryContentsItem {
  /**
   * Image field in *VisionFutureSection → Default → Primary → Contents*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_future_section.default.primary.contents[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *VisionFutureSection → Default → Primary → Contents*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_future_section.default.primary.contents[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Title Hovered field in *VisionFutureSection → Default → Primary → Contents*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_future_section.default.primary.contents[].title_hovered
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_hovered: prismic.RichTextField;

  /**
   * Content Hovered field in *VisionFutureSection → Default → Primary → Contents*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_future_section.default.primary.contents[].content_hovered
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content_hovered: prismic.RichTextField;
}

/**
 * Primary content in *VisionFutureSection → Default → Primary*
 */
export interface VisionFutureSectionSliceDefaultPrimary {
  /**
   * Name field in *VisionFutureSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_future_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *VisionFutureSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_future_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Contents field in *VisionFutureSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_future_section.default.primary.contents[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contents: prismic.GroupField<
    Simplify<VisionFutureSectionSliceDefaultPrimaryContentsItem>
  >;

  /**
   * Background field in *VisionFutureSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_future_section.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;
}

/**
 * Default variation for VisionFutureSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionFutureSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisionFutureSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VisionFutureSection*
 */
type VisionFutureSectionSliceVariation = VisionFutureSectionSliceDefault;

/**
 * VisionFutureSection Shared Slice
 *
 * - **API ID**: `vision_future_section`
 * - **Description**: VisionFutureSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionFutureSectionSlice = prismic.SharedSlice<
  "vision_future_section",
  VisionFutureSectionSliceVariation
>;

/**
 * Item in *VolunteerSection → Default → Primary → Actives*
 */
export interface VolunteerSectionSliceDefaultPrimaryActivesItem {
  /**
   * Name field in *VolunteerSection → Default → Primary → Actives*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: volunteer_section.default.primary.actives[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Content field in *VolunteerSection → Default → Primary → Actives*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: volunteer_section.default.primary.actives[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *VolunteerSection → Default → Primary*
 */
export interface VolunteerSectionSliceDefaultPrimary {
  /**
   * Name field in *VolunteerSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: volunteer_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *VolunteerSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: volunteer_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Actives field in *VolunteerSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: volunteer_section.default.primary.actives[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  actives: prismic.GroupField<
    Simplify<VolunteerSectionSliceDefaultPrimaryActivesItem>
  >;

  /**
   * Image field in *VolunteerSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: volunteer_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for VolunteerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VolunteerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VolunteerSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VolunteerSection*
 */
type VolunteerSectionSliceVariation = VolunteerSectionSliceDefault;

/**
 * VolunteerSection Shared Slice
 *
 * - **API ID**: `volunteer_section`
 * - **Description**: VolunteerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VolunteerSectionSlice = prismic.SharedSlice<
  "volunteer_section",
  VolunteerSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FootersDocument,
      FootersDocumentData,
      FootersDocumentDataFooterItemsItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataChildLinkItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSocicalsItem,
      SettingsDocumentDataNavigationsItem,
      SettingsDocumentDataFooterLinksItem,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutUsSectionSlice,
      AboutUsSectionSliceDefaultPrimaryAboutsItem,
      AboutUsSectionSliceDefaultPrimary,
      AboutUsSectionSliceVariation,
      AboutUsSectionSliceDefault,
      ActiveSectionSlice,
      ActiveSectionSliceDefaultPrimary,
      ActiveSectionSliceVariation,
      ActiveSectionSliceDefault,
      CaseStudiesSectionSlice,
      CaseStudiesSectionSliceDefaultPrimaryCasestudiesItem,
      CaseStudiesSectionSliceDefaultPrimary,
      CaseStudiesSectionSliceVariation,
      CaseStudiesSectionSliceDefault,
      EventSectionSlice,
      EventSectionSliceDefaultPrimary,
      EventSectionSliceVariation,
      EventSectionSliceDefault,
      ExploreNewSlice,
      ExploreNewSliceDefaultPrimary,
      ExploreNewSliceVariation,
      ExploreNewSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceHeroNewsPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSliceHeroNews,
      IndustrySectionSlice,
      IndustrySectionSliceDefaultPrimaryIndustrysItem,
      IndustrySectionSliceDefaultPrimary,
      IndustrySectionSliceVariation,
      IndustrySectionSliceDefault,
      LatestNewsSlice,
      LatestNewsSliceDefaultPrimary,
      LatestNewsSliceVariation,
      LatestNewsSliceDefault,
      NewMediaSectionSlice,
      NewMediaSectionSliceDefaultPrimary,
      NewMediaSectionSliceVariation,
      NewMediaSectionSliceDefault,
      PreviousNewSlice,
      PreviousNewSliceDefaultPrimary,
      PreviousNewSliceVariation,
      PreviousNewSliceDefault,
      ServiceSectionSlice,
      ServiceSectionSliceDefaultPrimaryServicesItem,
      ServiceSectionSliceDefaultPrimary,
      ServiceSectionSliceVariation,
      ServiceSectionSliceDefault,
      SolutionsGloballySectionSlice,
      SolutionsGloballySectionSliceDefaultPrimaryCarouselItem,
      SolutionsGloballySectionSliceDefaultPrimary,
      SolutionsGloballySectionSliceVariation,
      SolutionsGloballySectionSliceDefault,
      VisionFutureSectionSlice,
      VisionFutureSectionSliceDefaultPrimaryContentsItem,
      VisionFutureSectionSliceDefaultPrimary,
      VisionFutureSectionSliceVariation,
      VisionFutureSectionSliceDefault,
      VolunteerSectionSlice,
      VolunteerSectionSliceDefaultPrimaryActivesItem,
      VolunteerSectionSliceDefaultPrimary,
      VolunteerSectionSliceVariation,
      VolunteerSectionSliceDefault,
    };
  }
}
