// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_section: dynamic(() => import("./AboutUsSection")),
  active_section: dynamic(() => import("./ActiveSection")),
  case_studies_section: dynamic(() => import("./CaseStudiesSection")),
  event_section: dynamic(() => import("./EventSection")),
  explore_new: dynamic(() => import("./ExploreNew")),
  hero_section: dynamic(() => import("./HeroSection")),
  industry_section: dynamic(() => import("./IndustrySection")),
  latest_news: dynamic(() => import("./LatestNews")),
  new_media_section: dynamic(() => import("./NewMediaSection")),
  previous_new: dynamic(() => import("./PreviousNews")),
  service_section: dynamic(() => import("./ServiceSection")),
  solutions_globally_section: dynamic(
    () => import("./SolutionsGloballySection"),
  ),
  vision_future_section: dynamic(() => import("./VisionFutureSection")),
  volunteer_section: dynamic(() => import("./VolunteerSection")),
};
